### ISSUE TITLE
Can you please provide demo project for Kotlin?

### ISSUE THREAD

**Issue by IvanStanojevic** [pushy-me/pushy-demo-android#11]
Hello Team.
Thanks for your great Pushy.
Can you please provide demo project for Kotlin too?

Regards.

**Comment by pushy** [comment]
Hi @IvanStanojevic,
Thanks so much for your kind feedback and for bringing this to attention.

We've just finished releasing Kotlin-specific instructions for integrating the Pushy Android SDK:
https://pushy.me/docs/android/register-devices

At this time, the Pushy Demo project shall remain in Java. We may release a Kotlin version of this project in the future.
