### ISSUE TITLE
Jackson deserializer incorrectly translates values

### ISSUE THREAD

**Issue by vladaman** [pushy-me/pushy-demo-android#13]
Given two types of messages:

```json
{"val": 33}
```
and
```json
{"val": 33444444444444444}
```

One will be passed in Intent as Integer and second one as Long. This adds additional condition handling. Especially for complex JSON objects it becomes problem. Same applies to Double/Float numbers and Booleans with null.

I suggest you pass us original JSON so we can parse this ourselves properly. Pushy should not be handling this logic IMHO. Additionally I propose to remove Jackson dependency and rely on native JSON parse in Android to minimize third-party modules. For example we use Gson across our app.

**Comment by pushy** [comment]
Hi @vladaman,
Thanks for bringing this into our attention.

Our initial goal with passing the push payload via the intent extras was to simplify implementation for the developer, without having to require JSON parsing or value extraction, and provide a similar developer experience to GCM/FCM. However, we realize there are scenarios where accessing the raw JSON payload may be useful, such as in the scenario you presented, or when dealing with nested JSON objects.

Therefore, with version `1.0.64` of the [Pushy Android SDK](https://pushy.me/docs/android/get-sdk), we have introduced an intent extra `__json` which provides access to the raw JSON payload string in your push `BroadcastReceiver`:

```
String json = intent.getStringExtra("__json");
```

Import version `1.0.64` of the SDK as a dependency in your app's `build.gradle` to access the new functionality:

```
implementation 'me.pushy:sdk:1.0.64'
```

As per your recommendation with removing the Jackson dependency -- we will consider it for future versions.
