### ISSUE TITLE
Getting notification from Pushy and Firebase but need single notification

### ISSUE THREAD

**Issue by PristynCareMohit** [pushy-me/pushy-demo-android#15]

**Comment by pushy** [comment]
Hi @PristynCareMohit,
We're not entirely sure what you mean as the Pushy Android Demo project is not set up to receive notifications via Firebase. If you have a general inquiry regarding your own project, please reach out to support via e-mail at support@pushy.me.

**Comment by PristynCareMohit** [comment]
This is regarding an issue we are facing in your Android SDK. After implementing pushy android SDK in one of our project we encounter an issue of receiving the same notification twice i.e. from Firebase and pushy both, they are not in sync, followed all the steps mentioned in your documentation ref: https://pushy.me/docs/resources/fcm-fallback-delivery
