### ISSUE TITLE
Leak in Pushy Android

### ISSUE THREAD

**Issue by pyricau** [pushy-me/pushy-demo-android#17]
The leak was reporting in LeakCanary but really belongs here: https://github.com/square/leakcanary/issues/2159

I'm filing an issue here because I have no idea where to file an issue for pushy android.

```
    ┬───
    │ GC Root: Local variable in native code
    │
    ├─ java.lang.Thread instance
    │    Leaking: UNKNOWN
    │    Retaining 205 B in 5 objects
    │    Thread name: 'MQTT Call: fc307498c082fe03e987c4'
    │    ↓ Thread.target
    │             ~~~~~~
    ├─ me.pushy.sdk.lib.paho.internal.CommsCallback instance
    │    Leaking: UNKNOWN
    │    Retaining 296 B in 10 objects
    │    ↓ CommsCallback.mqttCallback
    │                    ~~~~~~~~~~~~
    ├─ me.pushy.sdk.util.PushyMqttConnection instance
    │    Leaking: UNKNOWN
    │    Retaining 2.9 kB in 27 objects
    │    mContext instance of me.pushy.sdk.services.PushyJobService
    │    ↓ PushyMqttConnection.mContext
    │                          ~~~~~~~~
    ╰→ me.pushy.sdk.services.PushyJobService instance
        Leaking: YES (ObjectWatcher was watching this because me.pushy.sdk.services.PushyJobService received
        Service#onDestroy() callback and Service not held by ActivityThread)
        Retaining 2.8 kB in 24 objects
        key = 1700a845-3541-40e5-ada1-719edb299264
        watchDurationMillis = 36527
        retainedDurationMillis = 31522
        mApplication instance of com.***.Application
        mBase instance of android.app.ContextImpl
```

PushyService is leaking, because the mqtt connection is still running and referencing it as a context instead of using the application context.

**Comment by pushy** [comment]
Hi @pyricau @maxxx,
Thanks so much for your report.

We've gone forth and patched this memory leak by saving a reference to `getApplicationContext()` instead of the current running instance of `JobService`. The fix will be made available once version `1.0.73` of the [Pushy Android SDK](https://pushy.me/docs/android/get-sdk) is released in the next week or two.

**Comment by pushy** [comment]
Hi @pyricau @maxxx,
Thanks so much for your patience.

Version `1.0.73` of the [Pushy Android SDK](https://pushy.me/docs/android/get-sdk) has just been released. Please import this new version in your app's `build.gradle`:

```
implementation 'me.pushy:sdk:1.0.73'
```

Then, rebuild and run your app, and let us know if the issue has been resolved.

**Comment by martinchiu1991** [comment]
It appears that this issue still happens on 1.0.73

**Comment by pushy** [comment]
Hi @martinchiu1991,
Thanks for reporting.

In versions `1.0.73` and up of the Pushy Android SDK, the referenced context in `PushyJobService` has been changed to the application context, so the exact leak reported in this issue should be fixed. 

Can you please create a new issue with the leak information reported by LeakCanary?
