### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by chiragshahopenxcell** [pushy-me/pushy-demo-android#2]
Hi Team,

I'm getting this error while deploying your demo.

**Android ssl: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate**

Please note:

I'm getting notification an almost al the device but there is one device Motorola MC40.In this device I'm getting this error.
![pushy_error](https://cloud.githubusercontent.com/assets/10704146/25215024/7d327500-25b8-11e7-8fff-19119fc13eaf.jpeg)

Please let me know what's this issue ASAP.

Thanks.

**Comment by pushy** [comment]
Hi @chiragshahopenxcell,
We have responded to your inquiry via e-mail.
