### ISSUE TITLE
Pushy Leaking in 1.0.79

### ISSUE THREAD

**Issue by martinchiu1991** [pushy-me/pushy-demo-android#20]
Issue is similar to https://github.com/pushy-me/pushy-demo-android/issues/17

Our project uses pushy 1.0.79 and this is the leak we get reported by leakcanary.

![Screen Shot 2022-03-16 at 12 02 41 PM](https://user-images.githubusercontent.com/97044196/158667628-f5a76040-73bf-42ad-8e0d-fe4e23337b95.png)

**Comment by pushy** [comment]
Hi @martinchiu1991,
Thanks so much for creating this issue.

We've just released version `1.0.80` of the [Pushy Android SDK](https://pushy.me/docs/android/get-sdk) which includes a fix for this leak. Please import this new version in your app's `build.gradle`:

```
implementation 'me.pushy:sdk:1.0.80'
```

Then, rebuild and run your app, and let us know if the issue has indeed been resolved.
