### ISSUE TITLE
Receiver not working on Android O 

### ISSUE THREAD

**Issue by yilmazgokhan** [pushy-me/pushy-demo-android#6]
It's working from API 19 to API 26. app opened or closed it's working all time. But on Android O and higher it's not working. When app opened or closed it's not working. I'm using pushy-demo-android's manifest and broadcastReceiver.

I tried debug on my Receiver class but when I use the app on Android O, the receiver' onReceive method not worked.
Any idea?

> Manifest:

`
        
        
        <receiver
            android:name=".Notification.PushReceiver"
            android:exported="false">
            <intent-filter>
                
                <action android:name="pushy.me" />
            </intent-filter>
        </receiver> 
        
        <receiver
            android:name="me.pushy.sdk.receivers.PushyUpdateReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver> 
        
        <receiver
            android:name="me.pushy.sdk.receivers.PushyBootReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver> 
        
        <service android:name="me.pushy.sdk.services.PushySocketService" /> 
        
        <service
            android:name="me.pushy.sdk.services.PushyJobService"
            android:exported="true"
            android:permission="android.permission.BIND_JOB_SERVICE" />`

`public class PushReceiver extends BroadcastReceiver {

    @Override
    public void onReceive(Context context, Intent intent) {
        String notificationTitle = "Title";
        String notificationText = "Text";

        /**/

        Bundle bundle = intent.getExtras();
        JSONObject jsonObject = new JSONObject();

        for (String key : bundle.keySet()) {
            try {
                jsonObject.put(key, wrap(bundle.get(key)));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        try {

            notificationText = jsonObject.get("body").toString();
            notificationTitle = jsonObject.get("title").toString();
        } catch (Exception e) {}

        // Prepare a notification with vibration, sound and lights
        NotificationCompat.Builder builder = new NotificationCompat.Builder(context)
                .setAutoCancel(true)
                .setSmallIcon(android.R.drawable.ic_dialog_info)
                .setContentTitle(notificationTitle)
                .setContentText(notificationText)
                .setLights(Color.RED, 1000, 1000)
                .setVibrate(new long[]{0, 400, 250, 400})
                .setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
                .setContentIntent(PendingIntent.getActivity(context, 0, new Intent(context, MainActivity.class), PendingIntent.FLAG_UPDATE_CURRENT));

        // Automatically configure a Notification Channel for devices running Android O+
        Pushy.setNotificationChannel(builder, context);

        // Get an instance of the NotificationManager service
        NotificationManager notificationManager = (NotificationManager) context.getSystemService(context.NOTIFICATION_SERVICE);

        // Build the notification and display it
        notificationManager.notify(1, builder.build());
`

And I use
`registerReceiver(broadcastReceiver, new IntentFilter("broadCastName"));`

**Comment by pushy** [comment]
Hi @yilmazgokhan,
1) Which version of the Pushy SDK are you using?

2) Please paste the contents of the following `adb` command to send us the device logs when it isn't receiving notifications:

```
adb logcat -d *:S Pushy
```

3) There is no need to call `registerReceiver`, as the receiver is called automatically by our SDK.

**Comment by pushy** [comment]
We believe this issue is no longer present in the latest Pushy Android SDK version. Please let us know if you can still reproduce this.
