### ISSUE TITLE
notworking in the latest version

### ISSUE THREAD

**Issue by ziahaqi** [pushy-me/pushy-demo-android#7]
i was trying to implement the latest version `v1.0.53` from the doc.  in this version  the notification isn't working. there is no incoming message.from API. and i got this error in the IDE log 
```/Pushy: Connect exception:  (0) - java.net.UnknownHostException: mqtt-1570433816.pushy.io```

in version `1.0.37` is working fine (same as the sample  version)

**Comment by pushy** [comment]
Hi @ziahaqi,
Thanks for reaching out, I'd be glad to assist.

It seems our new DNS servers in version `1.0.53` of the SDK are not returning a valid response for your request for some reason.

1) Can you open this link in your computer connected to the same network?
mqtt-1570433816.pushy.io

Does it work?

2) Can you please provide the output of running this command in your computer?

```
dig +trace mqtt-1570433816.pushy.io
```

3) Finally, you can still reference SDK `1.0.52` as it uses the old DNS servers if you do not have time to help us track down the issue. 

Thanks again!

**Comment by ziahaqi** [comment]
1. the response `{"healthy":true}`
2. the log 
```; <<>> DiG 9.10.6 <<>> +trace mqtt-1570433816.pushy.io
;; global options: +cmd
.                       518400  IN      NS      b.root-servers.net.
.                       518400  IN      NS      a.root-servers.net.
.                       518400  IN      NS      g.root-servers.net.
.                       518400  IN      NS      c.root-servers.net.
.                       518400  IN      NS      m.root-servers.net.
.                       518400  IN      NS      l.root-servers.net.
.                       518400  IN      NS      j.root-servers.net.
.                       518400  IN      NS      d.root-servers.net.
.                       518400  IN      NS      e.root-servers.net.
.                       518400  IN      NS      k.root-servers.net.
.                       518400  IN      NS      h.root-servers.net.
.                       518400  IN      NS      f.root-servers.net.
.                       518400  IN      NS      i.root-servers.net.
;; Received 239 bytes from 10.128.10.14#53(10.128.10.14) in 52 ms

io.                     172800  IN      NS      a0.nic.io.
io.                     172800  IN      NS      a2.nic.io.
io.                     172800  IN      NS      b0.nic.io.
io.                     172800  IN      NS      c0.nic.io.
io.                     86400   IN      DS      57355 8 1 434E91E206134F5B3B0AC603B26F5E029346ABC9
io.                     86400   IN      DS      57355 8 2 95A57C3BAB7849DBCDDF7C72ADA71A88146B141110318CA5BE672057 E865C3E2
io.                     86400   IN      RRSIG   DS 8 1 86400 20191021050000 20191008040000 22545 . dIwoOIgWXOIcapUHVy0LZtt84JY73jnjCJxoJ/1BYMmbUSA9w7TM1C2o ziPzGjd+mweaLmCxkeuo8L9SC10i3CSOfhZejRaIioF/7c9K8RUn3P1M MuNSb+wGl1MGvGhFpnKiChmZgwjklpi+5ZHsQGLpvBnG3+HIhdNHFLoC tI88lr1vV9MCdHY216yurashscw2HrJiVi2cGqWI5D7HcCjkczLreyA9 iFu4i6z87bARnaX+vxAR56rehipFfgUeDFx17CeYrws/34e1xPoe/NDa CE/lCeyxtRjStCF+WR4HMjyz9puV3iVuYsNO4Cs7HMDmwCTXZTOJ5qVA QtxNUQ==
;; Received 672 bytes from 192.58.128.30#53(j.root-servers.net) in 50 ms

pushy.io.               86400   IN      NS      ns1.pushy.me.
pushy.io.               86400   IN      NS      ns4.pushy.me.
pushy.io.               86400   IN      NS      ns2.pushy.me.
pushy.io.               86400   IN      NS      ns3.pushy.me.
2iui5t1khct6c5o8i2i67rppatgvegqo.io. 900 IN NSEC3 1 1 1 D399EAAB 2IV073DVU92DLMV2H5L9G1PEODM9RDE6  NS SOA RRSIG DNSKEY NSEC3PARAM
2iui5t1khct6c5o8i2i67rppatgvegqo.io. 900 IN RRSIG NSEC3 8 2 900 20191029073244 20191008063244 23793 io. ZgAnabhst4YiXSBFPRhK27EWCZjYm1tGgrEawgYl6XD5HOqkNO2WFHkT nrLfXfpbJf8WIBiYrGEk6cLa5RERjmXXlEaqpXZ7TyjHToJkMq+/e6+Y lfd0MvF/sjdJnY+ALWeiSix+KJvFAwFGYtGY5C6NUV9TY0wIMaHKxC4M /RU=
pkdi04bbjckhulm9v1gcpqtld3014h52.io. 900 IN NSEC3 1 1 1 D399EAAB PKER46VS598AV72TMAV76MD594135GK9  NS DS RRSIG
pkdi04bbjckhulm9v1gcpqtld3014h52.io. 900 IN RRSIG NSEC3 8 2 900 20191022151711 20191001141711 23793 io. t7HCbp5Z1GENaIMj0g99AjPzuGb8HHX9y+Z2dmMaNLb1fLXi2GN7/bm8 0y6lbLcptwu7Cz0/rt/FNzCTNN9BM1GDKB6/2YzW9aP/b6fZxmuG4HkT XqI2C38keY46ob7884UtrSVRJu1TedY5mqiziMhjWSujr2vKrAIr4hhH xPc=
;; Received 624 bytes from 65.22.161.17#53(b0.nic.io) in 332 ms

mqtt-1570433816.pushy.io. 3     IN      A       54.166.162.164
pushy.io.               172800  IN      NS      ns1.pushy.me.
pushy.io.               172800  IN      NS      ns2.pushy.me.
pushy.io.               172800  IN      NS      ns3.pushy.me.
pushy.io.               172800  IN      NS      ns4.pushy.me.
;; Received 138 bytes from 3.224.232.182#53(ns1.pushy.me) in 304 ms
```

**Comment by ziahaqi** [comment]
@pushy-me btw is it ok if i get the registered token to `Pushy.getDeviceCredentials(CONTEXT).token` since pushy sdk already store the token to pref ? 
because of the docs and the sample app don't have this information

**Comment by pushy** [comment]
Hi @ziahaqi,
Seems like your computer is able to resolve our DNS endpoint. Maybe it was a temporary network connectivity issue on your device? Is your device able to connect now or did you switch to the `1.0.52` SDK?

As per your question, the function `Pushy.register()` returns the most up-to-date device token, you can call this method and save the result as the device's current token.

You can still use the method `Pushy.getDeviceCredentials(CONTEXT).token` but the recommended approach is using `Pushy.register()` which also validates the currently-assigned token.

**Comment by ziahaqi** [comment]
i was rolling back the version to `1.0.52`, since the `v1.0.53` doesnt working.
>Maybe it was a temporary network connectivity issue on your device? Is your device able to connect now or did you switch to the 1.0.52 SDK?

i don't think so, it still not working in my computer

**Comment by pushy** [comment]
HI @ziahaqi,
Thanks for the additional information.

That's fine. You can keep using `1.0.52` without any issue.
