### ISSUE TITLE
Notification not working when the app is killed

### ISSUE THREAD

**Issue by NouranAmr** [pushy-me/pushy-demo-android#9]
I am testing Pushy sdk version 1.0.37 , it's working fine when the app is in foreground or background
but when i kill the app for the first time and send a notification, it is not received till i open the app again.
When i kill the app for the second time i can receive the notification just fine.
I tried it with different emulators with different Android api versions and its all the same
and on tablet Lenovo TB-7304I Api 24 an still the same issue.

**Comment by pushy** [comment]
Hi @NouranAmr,
Thanks for reaching out. I'd be glad to assist with your inquiry.

This issue has most likely been resolved in the latest Pushy Android SDK version, `1.0.55`:
https://pushy.me/docs/android/get-sdk

Please update the import statement in `app/build.gradle` as follows:
```
implementation 'me.pushy:sdk:1.0.55'
```

In addition, update your `AndroidManifest.xml` declarations:
https://pushy.me/docs/android/modify-androidmanifest

For further correspondence on this issue, please reply to the e-mail you sent us.
